apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/created-by: lws-operator
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: lws-operator
  name: lws-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lws-manager-role
subjects:
  - kind: ServiceAccount
    name: lws-controller-manager
    namespace: openshift-lws-operator
