apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/created-by: lws-operator
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: lws-operator
  name: lws-leader-election-rolebinding
  namespace: openshift-lws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lws-leader-election-role
subjects:
  - kind: ServiceAccount
    name: lws-controller-manager
    namespace: openshift-lws-operator
