apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-lws-operator
  namespace: openshift-lws-operator
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: /metrics
      port: "8443"
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: component
  selector:
    matchLabels:
      control-plane: controller-manager