apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    service.beta.openshift.io/serving-cert-secret-name: lws-webhook-server-cert
  labels:
    app.kubernetes.io/name: lws-operator
    control-plane: controller-manager
  name: lws-webhook-service
  namespace: openshift-lws-operator
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
