kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-lws-operator
subjects:
  - kind: ServiceAccount
    name: openshift-lws-operator
    namespace: openshift-lws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-lws-operator