apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lws-metrics-cert
  namespace: openshift-lws-operator
spec:
  commonName: lws-metrics
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: lws-selfsigned-issuer
  secretName: metrics-server-cert
