apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lws-prometheus-k8s
  namespace: openshift-lws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lws-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
- kind: ServiceAccount
  name: prometheus-operator
  namespace: openshift-monitoring
